config/routes.rb
Rails.application.routes.draw do

root to: 'public/homes#top'

  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] , controllers: {
    sessions: "admin/sessions"
  }

  # 管理者用
  namespace :admin do
    # top
    get '/' => 'homes#top'
    resources :items, except: [:destroy ]
    resources :genres, only: [:create, :index, :edit, :update ]
    resources :customers, only: [:index, :show, :edit, :update ]
    resources :orders, only: [:show, :update ]
    resources :order_details, only: [:update]
  end

  # 顧客用
  scope module: :public do
    get "/about" => 'homes#about'
    # customers
    get "customers/my_page" => 'customers#show'
    get "customers/infomation/edit" => 'customers#edit'
    patch "customers/infomation" => 'customers#update'
    get "customers/unsubscribe" => 'customers#unsubscribe'
    patch "customers/withdrawl" => 'customers#withdrawl'

    # cart_items
    delete "cart_items/destroy_all" => 'cart_items#destroy_all'

    # orders
    post "orders/confirm" => 'orders#confirm'
    get "orders/confirm" => 'orders#new'
    get "orders/complete" => 'orders#complete'

    resources :items, only: [:index, :show ]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy ]
    resources :cart_items, only: [:index, :create, :update, :destroy ]
    resources :orders, only: [:new, :create, :index, :show ]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  validates :amount, presence: true

  belongs_to :customer
  belongs_to :item

  # 小計を求めるメソッド
  def subtotal
    # with_tax_priceはitemモデルで定義
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  # validates :last_name_kana, presence: true, format: { with: /\A[\p{katakana}\u{30fc}]+\z/, message: 'カタカナで入力して下さい。'}
  validates :email, uniqueness: true
   
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy

   
      
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  validates :name, presence: true
  
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
validates :name, presence: true
  validates :introduction, presence: true
  validates :genre_id, presence: true
  validates :price, presence: true
  validates :is_active, inclusion: [ true, false]

  has_many  :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

  has_one_attached :item_image

  # 消費税メソッド
  def with_tax_price
    (price * 1.1).floor
  end

  def get_item_image(width, height)
    unless item_image.attached?
      file_path = Rails.root.join('app/assets/images/no-image.jpg')
      item_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    item_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { awaiting_payment: 0, payment_confirmation: 1, under_making: 2, preparing_to_ship: 3, shipped: 4 }

  has_many :order_details, dependent: :destroy
  belongs_to :customer
end

app/models/order_history_detail.rb
class OrderHistoryDetail < ApplicationRecord
  enum making_status: { not_available: 0, waiting_making: 1, making_progress: 2, completed: 3 }

  belongs_to :order
  belongs_to :item

  # 小計を求めるメソッド
  def subtotal
    # with_tax_priceはitemモデルで定義
    item.with_tax_price * amount
  end
end

app/controllers/admin/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customers = Customer.find(params[:id])
    @customers_name = @customer.last.name + @customer.first_name
  end
  
  def edit
  @customer = Customer.find(params[:id])
  @customer_name = @customer.last_name + @customer.first_name
  end
  
  
end

app/controllers/admin/genres_controller.rb
class GenresController < ApplicationController
  #ログインしていない状態で管理者ページにアクセスすると、ログイン画面へリダイレクト(adminは例外なし)
  before_action :authenticate_admin!
  
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "Genre was successfuly created."
      redirect_to admins_genres_path
    else
      flash[:notice] = "Genre was false created"
      @genres = Genre.all
      render :new
    end
  end
  
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def edit
    @genre = Genre. find(params[:id])
  end

  def update
    @genre = Genre. find(params[:id])
    if @genre.update(genre_params)
      flash[:notice] = "You have update genre successfully."
      redirect_to admin_genres_path
    else
      render :edit
    end
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
   #ログインしていない状態で管理者ページにアクセスすると、ログイン画面へリダイレクト
  before_action :authenticate_admin!

  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class ItemsController < ApplicationController
  #ログインしていない状態で管理者ページにアクセスすると、ログイン画面へリダイレクト(adminは例外なし)
  before_action :authenticate_admin!
  before_action :select_genres, only: [ :new, :create, :show, :edit, :update ]

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      # admin/items/showにリダイレクト
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "You have updated item successfully."
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit( :genre_id, :name, :introduction, :price, :is_active, :item_image )
  end

  def select_genres
    @genres = Genre.all
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/customers/edit.html.erb
<!--admin/customer/editページ-->
<div class="container">
  <div class="row mt-5">
    <h5><span class="px-3 bg-secondary text-light"><%= @customer_name %>さんの会員情報編集</span></h5>
  </div>
  <%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch, class: "form-group" do |f| %>
    <div class="mt-5 form-group row">
      <div class="col-2">
        会員ID
      </div>
      <div class="col">
        <%= @customer.id %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-2">
        氏名
      </div>
      <%= f.text_field :last_name, autofocus: true, class: "col-2 pl-1" %>
      <%= f.text_field :first_name, autofocus: true, class: "col-2 ml-5 pl-1" %>
    </div>
    
    <div class="form-group row">
      <div class="col-2">
        フリガナ
      </div>
      <%= f.text_field :last_name_kana, autofocus: true, class: "col-2 pl-1" %>
      <%= f.text_field :first_name_kana, autofocus: true, class: "col-2 ml-5 pl-1" %>
    </div>

    <div class="form-group row">
      <div class="col-2">
        郵便番号
      </div>
      <%= f.text_field :postal_code, autofocus: true, class: "col-2 pl-1" %>
    </div>

    <div class="form-group row">
      <div class="col-2">
        住所
      </div>
      <%= f.text_field :address, autofocus: true, class: "col-6 pl-1" %>
    </div>

    <div class="form-group row">
      <div class="col-2">
        電話番号
      </div>
      <%= f.text_field :telephone_number, autofocus: true, class: "col-2 pl-1" %>
    </div>

    <div class="form-group row">
      <div class="col-2">
        メールアドレス
      </div>
      <%= f.text_field :email, autofocus: true, class: "col-2 pl-1" %>
    </div>
    
    <div class="form-group row">
      <div class="col-2">
        会員ステータス
      </div>
      <div class="col pl-0">
        <%= f.radio_button :is_deleted, false %>
        <%= f.label :is_deleted, "有効", value: false, class: "mr-3 mb-0 border-bottom" %>
        <%= f.radio_button :is_deleted, true %>
        <%= f.label :is_deleted, "退会", value: true, class: "mb-0 border-bottom" %>
      </div>
    </div>

    <div class="form-group row mt-5">
      <%= f.submit "変更を保存", class: "offset-2 px-4 btn btn-success font-weight-bold" %>
    </div>
  <% end %>
</div>

app/views/admin/customers/index.html.erb
<!--admin/customer/indexページ-->
<div class="container">
  <div class="row mt-5">
    <div class="offset-1">
      <h5 class="ml-4"><span class="px-3 bg-secondary text-light">会員一覧</span></h5>
    </div>
  </div>
  <div class="row mt-2">
    <div class="offset-2 col-8">
      <table class="table table-sm  border-bottom">
        <thead class="table-secondary ">
          <tr>
            <th style="width: 10%">会員ID</th>
            <th style="width: 30%">氏名</th>
            <th style="width: 40%">メールアドレス</th>
            <th style="width: 20%">ステータス</th>
          </tr>
        </thead>
        <% @customers.each do |customers| %>
          <tbody class="">
            <tr>
              <td><%= customers.id %></td>
              <td>
                <%= link_to admin_customer_path(customers.id), class: "text-dark" do%>
                  <%= customers.last_name %><%= customers.first_name %>
                <% end %>
              </td>
              <td><%= customers.email %></td>
              <td>
                <% if customers.is_deleted %>
                  <strong class="text-secondary font-weight-bold"><%= customers.is_deleted ? "退会" : "有効" %></strong>
                <% else %>
                  <strong class="text-success font-weight-bold"><%= customers.is_deleted ? "退会" : "有効" %></strong>
                <% end %>
              </td>
            </tr>
          </tbody>
        <% end %>
      </table>
      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<!--admin/customer/showページ-->
<div class="container">
  <div class="row mt-5">
    <h5><span class="px-3 bg-secondary text-light"><%= @customer_name %>さんの会員詳細</span></h5>
  </div>
  <div class="mt-5 form-group row">
    <div class="col-2">
    会員ID
    </div>
    <div class="col-2">
      <%= @customer.id %>
    </div>
  </div>
  
  <div class="form-group row">
    <div class="col-2">
    氏名
    </div>
    <div class="col-2">
      <%= @customer.last_name %><%= @customer.first_name %>
    </div>
  </div>
  
  <div class="form-group row">
    <div class="col-2">
      フリガナ
    </div>
    <div class="col-2">
      <%= @customer.last_name_kana %><%= @customer.first_name_kana %>
    </div>
  </div>
  
  <div class="form-group row">
    <div class="col-2">
      郵便番号
    </div>
    <div class="col-2">
      <%= @customer.postal_code %>
    </div>
  </div>
  
  <div class="form-group row">
    <div class="col-2">
      住所
    </div>
    <div class="col-2">
      <%= @customer.address %>
    </div>
  </div>
  
  <div class="form-group row">
    <div class="col-2">
      電話番号
    </div>
    <div class="col-2">
      <%= @customer.telephone_naumber %>
    </div>
  </div>
  
  <div class="form-group row">
    <div class="col-2">
      メールアドレス
    </div>
    <div class="col-2">
      <%= @customer.email %>
    </div>
  </div>
  
  <div class="form-group row">
    <div class="col-2">
      会員ステータス
    </div>
    <div class="col-2">
      <%= if @customer.is_deleted %>
       <strong class="text-secondary font-weight-bold"><%= @customer.isdeleted ? "退会" : "有効" %></strong>
      <% else %>
       <strong class="text-success font-weight-bold"><%= @customer.is_deleted ? "退会" : "有効" %></strong>
      <% end %>
    </div>
   </div>
   <div class="form-group row">
    <%= link_to "編集する", edit_admin_customer_path(@customer.id), class: "offset-2 col-1 btn btn-success" %>
    <%= link_to "注文一覧を見る", admin_path, class: "offset-1 px-3 btn-primary" %>
   </div>
  </div>