config/routes.rb
Rails.application.routes.draw do

root to: 'public/homes#top'

  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] , controllers: {
    sessions: "admin/sessions"
  }

  # 管理者用
  namespace :admin do
    # top
    get '/' => 'homes#top'
    resources :items, except: [:destroy ]
    resources :genres, only: [:create, :index, :edit, :update ]
    resources :customers, only: [:index, :show, :edit, :update ]
    resources :orders, only: [:show, :update ]
    resources :order_details, only: [:update]
  end

  # 顧客用
  scope module: :public do
    get "/about" => 'homes#about'
    # customers
    get "customers/my_page" => 'customers#show'
    get "customers/infomation/edit" => 'customers#edit'
    patch "customers/infomation" => 'customers#update'
    get "customers/unsubscribe" => 'customers#unsubscribe'
    patch "customers/withdrawl" => 'customers#withdrawl'

    # cart_items
    delete "cart_items/destroy_all" => 'cart_items#destroy_all'

    # orders
    post "orders/confirm" => 'orders#confirm'
    get "orders/confirm" => 'orders#new'
    get "orders/complete" => 'orders#complete'

    resources :items, only: [:index, :show ]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy ]
    resources :cart_items, only: [:index, :create, :update, :destroy ]
    resources :orders, only: [:new, :create, :index, :show ]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  validates :amount, presence: true

  belongs_to :customer
  belongs_to :item

  # 小計を求めるメソッド
  def subtotal
    # with_tax_priceはitemモデルで定義
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  # validates :last_name_kana, presence: true, format: { with: /\A[\p{katakana}\u{30fc}]+\z/, message: 'カタカナで入力して下さい。'}
  validates :email, uniqueness: true
   
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy

   
      
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  validates :name, presence: true
  
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
validates :name, presence: true
  validates :introduction, presence: true
  validates :genre_id, presence: true
  validates :price, presence: true
  validates :is_active, inclusion: [ true, false]

  has_many  :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

  has_one_attached :item_image

  # 消費税メソッド
  def with_tax_price
    (price * 1.1).floor
  end

  def get_item_image(width, height)
    unless item_image.attached?
      file_path = Rails.root.join('app/assets/images/no-image.jpg')
      item_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    item_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { awaiting_payment: 0, payment_confirmation: 1, under_making: 2, preparing_to_ship: 3, shipped: 4 }

  has_many :order_details, dependent: :destroy
  belongs_to :customer
end

app/models/order_history_detail.rb
class OrderHistoryDetail < ApplicationRecord
  enum making_status: { not_available: 0, waiting_making: 1, making_progress: 2, completed: 3 }

  belongs_to :order
  belongs_to :item

  # 小計を求めるメソッド
  def subtotal
    # with_tax_priceはitemモデルで定義
    item.with_tax_price * amount
  end
end

app/controllers/admin/genres_controller.rb
class GenresController < ApplicationController
  #ログインしていない状態で管理者ページにアクセスすると、ログイン画面へリダイレクト(adminは例外なし)
  before_action :authenticate_admin!
  
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "Genre was successfuly created."
      redirect_to admins_genres_path
    else
      flash[:notice] = "Genre was false created"
      @genres = Genre.all
      render :new
    end
  end
  
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def edit
    @genre = Genre. find(params[:id])
  end

  def update
    @genre = Genre. find(params[:id])
    if @genre.update(genre_params)
      flash[:notice] = "You have update genre successfully."
      redirect_to admin_genres_path
    else
      render :edit
    end
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
   #ログインしていない状態で管理者ページにアクセスすると、ログイン画面へリダイレクト
  before_action :authenticate_admin!

  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class ItemsController < ApplicationController
  #ログインしていない状態で管理者ページにアクセスすると、ログイン画面へリダイレクト(adminは例外なし)
  before_action :authenticate_admin!
  before_action :select_genres, only: [ :new, :create, :show, :edit, :update ]

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      # admin/items/showにリダイレクト
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "You have updated item successfully."
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit( :genre_id, :name, :introduction, :price, :is_active, :item_image )
  end

  def select_genres
    @genres = Genre.all
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admins::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end
  
  protected
   def after_sign_in_path_for(resource)
     admin_items_path
   end
   
   def after_sign_out_path_for(resource)
     new_admin_session_path
   end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/genres/create.html.erb
<h1>Genres#create</h1>
<p>Find me in app/views/genres/create.html.erb</p>

app/views/admin/genres/edit.html.erb
<!--admin/genres/editページ-->
<div class="container">
  <div class="row mt-5">
    <div class="offset-1 col-2 text-center bg-secondary text-light">
      <h5 class="mb-0">ジャンル編集</h5>
    </div>
  </div>
  <div class="row mt-5 ">
    <div class="form-inline">
      <%= form_with model: @genre, url: admin_genre_path(@genre.id), method: :patch, class:"form-group" do |f| %>
        <div class="mx-5 my-auto"><p class="mb-0">ジャンル名</p></div>
        <%= f.text_field :name, autofocus: true, placeholder: "ジャンル名", class:"border border-dark mr-5" %>
        <%= f.submit "変更を保存", class: "btn btn-sm rounded-3 py-1 px-3 btn-success font-weight-bold" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<!-- admin/genres/indexページ -->
<div class="container">
  <div class="row mt-5">
     <div class="ml-5"><h5 class="px-3 bg-dark text-light">ジャンル一覧・追加</h5></div>
</div>


<!-- ジャンル新規登録 -->
<%= form_with model: [:admin, @genre], method: :post do |f| %>
  <div class="row mt-3 ml-3 form-inline form-group">
    <div class="col-1 pl-0">
      <label>ジャンル名</label>
    </div>
    <%= f.text_field :name, autofocus: true, :placeholder => "ジャンル名", class: "p-0 col-2 border border-dark" %>
    <%= f.submit "新規登録", class: "col-1 ml-5 px-4 btn btn-succes font-weight-bold" %>
  </div>
<% end %>  
  
<!-- ジャンル一覧 -->
 <div class="row mt-4 ml-3">
  <div class="col-3 px-0">
    <table class="table table-sm border-top border-bottom ">
      <thead class="table-secondary">
        <tr>
          <th  class="text-center" style="width: 50%">ジャンル</th>
          <th style="width: 50%"></th>
        </tr>
      </thead>
      <% @genres.each do |genres| %>
        <tbody>
          <tr>
            <td>
              <%= genres.name %>
            </td>
            <td class="text-center">
              <%= link_to edit_admin_genre_path(genres.id), class: "btn btn-sm btn-success" do %>
                編集する
              <% end %>
            </td>
          </tr>
        </tbody>
      <% end %>
    </table>
  </div>
 </div>
</div>

app/views/admin/genres/new.html.erb
<h1>Genres#new</h1>
<p>Find me in app/views/genres/new.html.erb</p>

app/views/admin/genres/update.html.erb
<h1>Genres#update</h1>
<p>Find me in app/views/genres/update.html.erb</p>

app/views/admin/homes/top.html.erb
<!--admin/topページ(注文履歴一覧 #index)-->
<div class="container">
  <div class="row mt-5">
    <h5><span class="px-3 bg-secondary text-light">注文履歴一覧</span></h5>
  </div>

  <div class="row">
    <table class="col table border-bottom">
      <thead class="table-secondary text-dark">
        <th style>購入日時</th>
        <th>購入者</th>
        <th>注文個数</th>
        <th>注文ステータス</th>
      </thead>
      <% @orders.each do |order| %>
        <tbody>
          <tr>
            <td>
              <%= link_to admin_order_path(order.id), class: "text-body" do %>
                <%= order.created_at.strftime('%Y/%m/%d %T') %>
              <% end %>
            </td>
            <td>
              <%= order.customer.last_name %><%= order.customer.first_name %>
            </td>
            <td>
              <% order_total_amount = 0 %>
              <% order.order_details.each do |order_detail| %>
                <% order_total_amount += order_detail.amount %>
              <% end %>
              <%= order_total_amount %>
            </td>
            <td>
              <%= order.status_i18n %>
            </td>
          </tr>
        </tbody>
      <% end %>

    </table>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="offset-2">
      <h5 class="px-3 mb-0 bg-secondary text-light">商品編集</h5>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-8 offset-2">
      <%= form_with model: @item, url: admin_item_path(@item.id), method: :patch, class: "form-group" do |f| %>
        <table>
          <thead>
            <th style="width: 30%"></th>
            <th style="width: 70%"></th>
          </thead>
          <tbody>
            <tr>
              <td>商品画像</td>
              <td><%= f.file_field :item_image, placeholder: "ファイルを選択", accept: "image/*", class: "form-container-file" %></td>
            </tr>
            <tr>
              <td><%= f.label :name,class: "mb-0" %></td>
              <td><%= f.text_field :name, autofocus: true, placeholder: "商品名", class: "form-control" %></td>
            </tr>
            <tr>
              <td class="align-top"><%= f.label :introduction, class: "mb-0" %></td>
              <td><%= f.text_area :introduction, autofocus: true, placeholder: "ここに説明文を記述します", class: "form-control" %></td>
            </tr>
            <tr>
              <td>ジャンル</td>
              <td><%= f.collection_select :genre_id, @genres, :id, :name, {include_blank: "--選択してください--" } %></td>
            </tr>
            <tr>
              <td><%= f.label :price, class: "mb-0" %></td>
              <td class="form-inline"><%= f.text_field :price, autofocus: true, placeholder: "1000", class: "form-control" %>円</td>
            </tr>
            <tr>
              <td><%= f.label :is_active, class: "mb-0" %></td>
              <td>
                <%= f.radio_button :is_active, true, autofocus: true %>
                <%= f.label :is_active, "販売中", value: true, class: "mr-3 mb-0 border-bottom" %>
                <%= f.radio_button :is_active, false, autofocus: true %>
                <%= f.label :is_active, "販売停止中", value: false, class: "mb-0 border-bottom" %>
              </td>
            </tr>
          </tbody>
        </table>
        <div class="form-group mt-4">
          <%= f.submit "変更を保存", class: "offset-4 py-2 px-4 btn btn-success font-weight-bold" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="offset-1 my-auto ml-5">
      <h5 class="px-3 mb-0 bg-secondary text-light">商品一覧</h5>
    </div>
    <div class="col-1 ml-auto mr-5">
      <%= link_to new_admin_item_path, class: "p-0 btn btn-light btn-outline-dark border rounded-circle bg-secondary" do %>
        <h4 class="m-0 p-1 d-flex align-items-center text-dark bg-light rounded-circle font-weight-bold btn-shadow" style="weght: 30px; height: 30px;">+</h4>
      <% end %>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-12">
    <table class="table table-borderless border-top border-bottom borborder-secondary">
        <thead class="table-sm table-secondary">
          <tr>
            <th style="width: 10%">商品ID</th>
            <th style="width: 30%">商品名</th>
            <th style="width: 10%">税抜価格</th>
            <th style="width: 30%">ジャンル</th>
            <th style="width: 20%">ステータス</th>
          </tr>
        </thead>
        <% @items.each do |items| %>
          <tbody>
            <tr>
              <td><%= items.id %></td>
              <td>
                <%= link_to admin_item_path(items.id), class: "text-body" do %>
                  <%= items.name %>
                <% end %>
              </td>
              <td><%= items.price.to_s(:delimited) %></td>
              <td><%= items.genre.name %></td>
              <td>
                <% if items.is_active %>
                  <strong class="align-moddle text-success"><%= items.is_active ? "販売中" : "販売停止中" %></strong>
                <% else %>
                  <strong class="align-moddle text-secondary"><%= items.is_active ? "販売中" : "販売停止中" %></strong>
                <% end %>
              </td>
            </tr>
          </tbody>
        <% end %>
      </table>
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <!--商品新規登録フォーム-->
  <div class="row mt-4">
    <div class="offset-2 px-3 bg-secondary text-light">
      <h5>商品新規登録</h5>
    </div>
  </div>
  <div class="row mt-3">
    <div class="offset-3 col-8">
      
      
      <%= form_with model: @item, url:admin_items_path, method: :post do |f| %>
           <table>
             <thead>
               <th style="width: 30%"></th>
               <th style="width: 70%"></th>
             </thead>
             <tbody>
               <tr>
                 <td>商品画像</td>
                 <td><%= f.file_field :name, autofocus: true, placeholder: "ファイルを選択", accept: "image/*", class "form-container-file" %></td>
               </tr>
               <tr>
                 <td><%= f.label :name,class: "mb-0" %></td>
                 <td><%= f.label :name, autofocus: true, placeholder: "商品名", class: "form-control border border-dark" %></td>
               </tr>
               <tr>
                 <td class="align-top"><%= f.label :introduction, class: "mb-0" %></td>
                 <td><%=f.text_area :introductin, autofocus: true, placeholder: "説明文の記述", class: "form-control border border-dark" %></td>
               </tr>
               <tr>
                 <td>ジャンル</td>
                 <td><%= f.collection_select :genre_id, @genres, :id, :name, {include_blank: "--選択してください--"} %></td>
               </tr>
               <tr>
                 <td><%= f.label :price, class: "mb-0" %></td>
                 <td class="form-inline"><%= f.text_field :price, autofocus: true, placeholder: "1000", class: "form-control border border-dark" %></td><span>円</span>
               </tr>
               <tr>
                 <td><%= f.label :is_active, class: "mb-0" %></td>
                 <td>
                   <%= f.radio_buttun :is_active, true %>
                   <%= f.label :is_active, "販売中", value: true, class: "mr-3 mb-0 border-bottom" %>
                   <%= f.radio_buttun :is_active, false %>
                   <%= f.label :is_active, "販売停止中", value: false, class: "mb-0 border-bottom" %>
                 </td>
               </tr>
             </tbody>
           </table>
        <div class="form-group mt-4">
          <%= f.submit "新規登録", class: "offset-4 py-2 px-4 btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="offset-1">
      <h5><span class="px-3 bg-secondary text-light">商品詳細</span></h5>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-2 offset-2">
      <%= image_tag @item.get_item_image(150,200), class: "d-block ml-auto" %>
    </div>
    
    <div class="col-5">
      <table>
        <thead>
        <th style="width 30%"></th>
        <th style="width 70%"></th>
        </thead>
        <thody>
        <tr>
            <td>商品名</td>
            <td><%= @item.name %></td>
        </tr>
        <tr>
            <td class="align-top">商品説明</td>
            <td><%= @item.introduction %></td>
        </tr>
        <tr>
            <td>ジャンル</td>
            <td><%= @item.genre.name %></td>
        </tr>
        <tr>
            <td>税込価格<br>（税込価格）</td>
        </tr>
        <tr>
          <td>販売ステータス</td>
          <td>
            <% if @item.is_active %>
              <strong class="align-moddle text-success"><%= @item,is_active ? "販売中" : "販売停止中" %></strong>
            <% else %>
              <strong class="align-moddle text-secondary"><%= @item.is_active ? "販売中" : "販売停止中" %></strong>
            <% end %>
          </td>
        </tr>  
        </thody>
      </table>
      <%= link_to "編集する",edit_admin_item_path(@item.id), class: "offset-3 mt-3 py-2 px-4 btn btn-success" %>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<!--admin/orders/showページ-->
<div class="container-fluid">
  <div class="row mt-3">
    <div class="offset-1">
      <h5><span class="px-3 bg-secondary text-light">注文履歴詳細</span></h5>
    </div>
  </div>
  <div class="row ml-5">
    <div class="col-2">
      <strong>購入者</strong>
    </div>
    <div class="col-2">
      <%= @customer_name %>
    </div>
  </div>
  <div class="row ml-5">
    <div class="col-2">
      <strong>注文日</strong>
    </div>
    <div class="col-2">
      <%= @order.created_at.strftime('%Y/%m/%d') %>
    </div>
  </div>
  <div class="row ml-5">
    <div class="col-2">
      <strong>配送先</strong>
    </div>
    <div class="col-2">
      〒<%= @order.shipping_postal_code.to_s.insert(3, "-") %> <%= @order.shipping_address %><br>
      <%= @order.shipping_name %>
    </div>
  </div>
  <div class="row ml-5">
    <div class="col-2">
      <strong>支払方法</strong>
    </div>
    <div class="col-2">
      <%= @order.payment_method_i18n %>
    </div>
  </div>
  <div class="row ml-5 d-flex align-items-center">
    <div class="col-2">
      <strong>注文ステータス</strong>
    </div>
    <%= form_with model: @order, url: admin_order_path(@order.id), method: :patch , class: "col d-flex align-items-center" do |f| %>
      <%= f.select :status, Order.statuses.keys.map{ |k| [I18n.t("enums.order.status.#{k}"), k] } %>
      <%= f.submit "更新", class: "px-1 btn btn-sm btn-success ml-5" %>
    <% end %>
  </div>
  <div class="row mt-4 ml-5">
    <table class="col-7 table table-sm table-dark table-borderless border-top border-bottom border-secondary">
      <thead class="table-secondary text-dark">
        <tr>
          <th style="width: 20%">商品名</th>
          <th style="width: 20%">単価(税込)</th>
          <th style="width: 20%">数量</th>
          <th style="width: 20%">小計</th>
          <th style="width: 20%">制作ステータス</th>
        </tr>
      </thead>
      <% @order.order_details.each do |order_detail| %>
      <tbody class="table-light text-dark">
        <tr>
          <td class="align-middle">
            <%= order_detail.item.name %>
          </td>
          <td class="align-middle">
            <%= order_detail.item.with_tax_price.to_s(:delimited) %>
          </td>
          <td class="align-middle">
            <%= order_detail.amount %>
          </td>
          <td class="align-middle">
            <%= order_detail.subtotal.to_s(:delimited) %>
          </td>
          <td>
            <%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id), method: :patch , class: "d-flex align-items-center justify-content-around" do |f| %>
              <%= f.select :making_status, OrderDetail.making_statuses.keys.map { |k| [I18n.t("enums.order_detail.making_status.#{k}"), k] } %>
              <%= f.submit "更新", class: "btn btn-sm btn-success px-1" %>
            <% end %>
          </td>
        </tr>
      </tbody>
      <% end %>
    </table>
    <div class="ml-5 mr-5 col-2 align-self-end">
    <table class="table-sm">
      <tbody>
        <tr>
          <th>商品合計</th>
          <td>
            <%= @order_item_total_price.to_s(:delimited) %>円
          </td>
        </tr>
        <tr>
          <th>送料</th>
          <td>
            <%= @order.postage.to_s(:delimited) %>円
          </td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          <td>
            <strong><%= @order.amount_billed.to_s(:delimited) %>円</strong>
          </td>
        </tr>
      </tbody>
    </table>
    </div>
  </div>

</div>