config/routes.rb
Rails.application.routes.draw do

root to: 'public/homes#top'

  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] , controllers: {
    sessions: "admin/sessions"
  }

  # 管理者用
  namespace :admin do
    # top
    get '/' => 'homes#top'
    resources :items, except: [:destroy ]
    resources :genres, only: [:create, :index, :edit, :update ]
    resources :customers, only: [:index, :show, :edit, :update ]
    resources :orders, only: [:show, :update ]
    resources :order_details, only: [:update]
  end

  # 顧客用
  scope module: :public do
    get "/about" => 'homes#about'
    # customers
    get "customers/my_page" => 'customers#show'
    get "customers/infomation/edit" => 'customers#edit'
    patch "customers/infomation" => 'customers#update'
    get "customers/unsubscribe" => 'customers#unsubscribe'
    patch "customers/withdrawl" => 'customers#withdrawl'

    # cart_items
    delete "cart_items/destroy_all" => 'cart_items#destroy_all'

    # orders
    post "orders/confirm" => 'orders#confirm'
    get "orders/confirm" => 'orders#new'
    get "orders/complete" => 'orders#complete'

    resources :items, only: [:index, :show ]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy ]
    resources :cart_items, only: [:index, :create, :update, :destroy ]
    resources :orders, only: [:new, :create, :index, :show ]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  validates :amount, presence: true

  belongs_to :customer
  belongs_to :item

  # 小計を求めるメソッド
  def subtotal
    # with_tax_priceはitemモデルで定義
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  # validates :last_name_kana, presence: true, format: { with: /\A[\p{katakana}\u{30fc}]+\z/, message: 'カタカナで入力して下さい。'}
  validates :email, uniqueness: true
   
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy

   
      
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  validates :name, presence: true
  
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
validates :name, presence: true
  validates :introduction, presence: true
  validates :genre_id, presence: true
  validates :price, presence: true
  validates :is_active, inclusion: [ true, false]

  has_many  :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

  has_one_attached :item_image

  # 消費税メソッド
  def with_tax_price
    (price * 1.1).floor
  end

  def get_item_image(width, height)
    unless item_image.attached?
      file_path = Rails.root.join('app/assets/images/no-image.jpg')
      item_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    item_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { awaiting_payment: 0, payment_confirmation: 1, under_making: 2, preparing_to_ship: 3, shipped: 4 }

  has_many :order_details, dependent: :destroy
  belongs_to :customer
end

app/models/order_history_detail.rb
class OrderHistoryDetail < ApplicationRecord
  enum making_status: { not_available: 0, waiting_making: 1, making_progress: 2, completed: 3 }

  belongs_to :order
  belongs_to :item

  # 小計を求めるメソッド
  def subtotal
    # with_tax_priceはitemモデルで定義
    item.with_tax_price * amount
  end
end

app/controllers/admin/genres_controller.rb
class GenresController < ApplicationController
  #ログインしていない状態で管理者ページにアクセスすると、ログイン画面へリダイレクト(adminは例外なし)
  before_action :authenticate_admin!
  
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "Genre was successfuly created."
      redirect_to admins_genres_path
    else
      flash[:notice] = "Genre was false created"
      @genres = Genre.all
      render :new
    end
  end
  
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def edit
    @genre = Genre. find(params[:id])
  end

  def update
    @genre = Genre. find(params[:id])
    if @genre.update(genre_params)
      flash[:notice] = "You have update genre successfully."
      redirect_to admin_genres_path
    else
      render :edit
    end
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
   #ログインしていない状態で管理者ページにアクセスすると、ログイン画面へリダイレクト
  before_action :authenticate_admin!

  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class ItemsController < ApplicationController
  #ログインしていない状態で管理者ページにアクセスすると、ログイン画面へリダイレクト(adminは例外なし)
  before_action :authenticate_admin!
  before_action :select_genres, only: [ :new, :create, :show, :edit, :update ]

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      # admin/items/showにリダイレクト
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "You have updated item successfully."
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit( :genre_id, :name, :introduction, :price, :is_active, :item_image )
  end

  def select_genres
    @genres = Genre.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/7d4686f8ad.js" crossorigin="anonymous"></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- ヘッダー -->
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark"> <!-- ここのtext-light はほかのページリンク作成したら消す-->
        <div class="container-fluid">
          <%= link_to root_path, class: "navbar-brand" do %>
            <h1 class="font-weight-lighter font-italic">nagano-cake</h1>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse navbar-expand-sm" id="navbarNavDropdown">
            <div class="mr-lg-auto ml-lg-5">
              <p class="mb-0 text-light">
                <%if customer_signed_in? %>
                ようこそ、<%= current_customer.last_name %>さん！
                <% end %>
              </p>
            </div>
            <ul class="nav navbar-nav w-60 nav-justified  ml-auto">
              <!-- admin サインイン -->
              <% if admin_signed_in? %>
                <li class="ml-lg-auto" style="width: 20%">
                  <%= link_to "商品一覧", admin_items_path, class: "btn btn-outline-light text-light d-block w-90 ml-auto" %>
                </li>
                <li class="" style="width: 20%">
                  <%= link_to "会員一覧", admin_customers_path, class: "btn btn-outline-light text-light d-block w-90 ml-auto" %>
                </li>
                <li class="" style="width: 20%">
                  <%= link_to "注文一覧", admin_path, class: "btn btn-outline-light text-light d-block w-90 ml-auto" %>
                </li>
                <li class="" style="width: 20%">
                  <%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-outline-light text-light d-block w-90 ml-auto" %>
                </li>
                <li class="" style="width: 20%">
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-light text-light d-block w-90 ml-auto" %>
                </li>
              <!-- customer サインイン -->
              <% elsif customer_signed_in? %>
                <li class="ml-lg-auto"  style="width: 20%">
                  <%= link_to "マイページ", customers_my_page_path, class: 'btn btn-outline-light text-light d-block w--90 ml-auto' %>
                </li>
                <li style="width: 20%">
                  <%= link_to "商品一覧", items_path, class: 'btn btn-outline-light text-light d-block w-90 ml-auto' %>
                </li>
                <li style="width: 20%">
                  <%= link_to "カート", cart_items_path, class: 'btn btn-outline-light text-light d-block w-90 ml-auto' %>
                </li>
                <li style="width: 20%">
                  <%= link_to "サインアウト", destroy_customer_session_path, method: :delete, class: 'btn btn-outline-light text-light d-block w-90 ml-auto' %>
                </li>
              <!-- 未ログイン -->
              <% else %>
                <li class="ml-lg-auto" style="width: 20%">
                  <%= link_to "About", about_path, class: 'btn btn-outline-light text-light d-block w-80 ml-auto' %>
                </li>
                <li style="width: 20%">
                  <%= link_to "商品一覧", items_path, class: 'btn btn-outline-light text-light d-block w-80 ml-auto' %>
                </li>
                <li style="width: 20%">
                  <%= link_to "新規登録", new_customer_registration_path, class: 'btn btn-outline-light text-light d-block w-80 ml-auto' %>
                </li>
                <li style="width: 20%">
                  <%= link_to "ログイン", new_customer_session_path, class: 'btn btn-outline-light text-light d-block w-80 ml-auto' %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <!-- メイン -->
    <main>
      <%= yield %>
    </main>
    <!-- フッター -->
    <footer>
      <div class="container-fulled mt-5 bg-dark">
        <div class="row">
          <div class="mx-auto">
            <p class="text-light mb-0">nagano cake</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>